default_config:

#lovelace:  
#  mode: yaml

logger:
  default: debug

mqtt:  
  broker: mqtt
  discovery: true
  discovery_prefix: homeassistant
  
switch:
  - platform: mqtt
    name: s20
    state_topic: s20/relay/0
    command_topic: s20/relay/0/set
    payload_on: 1
    payload_off: 0

shell_command:
  - light_on: python3 /lights/lights_on.py
  - light_off: python3 /lights/lights_off.py 

script:
  lights_on:
    alias: 'Turn the lights on'
    sequence:
      service: shell_command.light_on
  lights_off:
    alias: 'Turn the lights off'
    sequence:
      service: shell_command.light_off        