default_config:

lovelace:  
  mode: yaml

logger:
  default: debug

mqtt:  
  broker: mqtt
  discovery: true
  discovery_prefix: homeassistant
  
switch:
  - platform: mqtt
    name: s20
    state_topic: s20/relay/0
    command_topic: s20/relay/0/set
    payload_on: 1
    payload_off: 0

shell_command:
  light_on: python3 /lights/lights.py  