
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # http:
  #   base_url: example.duckdns.org:8123
  
  # Text to speech
  tts:
    - platform: google_translate
  
  group: !include groups.yaml
  automation: !include automations.yaml
  script: !include scripts.yaml
  scene: !include scenes.yaml
  
  mqtt:  
    broker: mqtt
    discovery: true
    discovery_prefix: homeassistant
    
  switch:
    - platform: mqtt
      name: s20
      state_topic: s20/relay/0
      command_topic: s20/relay/0/set
      payload_on: 1
      payload_off: 0

  shell_command:
    light_on: python3 /lights/lights.py      